//  This file is automatically generated. DO NOT EDIT, all your changes would be lost.
//  https://pub.dartlang.org/packages/iconfont_convert

import 'package:flutter/material.dart';

class HyIcons {
  static const String _family = 'HyIcons';
  
  HyIcons._();
  
  static const IconData gengduocaozuo = IconData(0xe627, fontFamily: _family); // 更多操作
  static const IconData jiantou = IconData(0xe628, fontFamily: _family); // 箭头
  static const IconData bianji = IconData(0xe61a, fontFamily: _family); // 编辑
  static const IconData guanbi = IconData(0xe61c, fontFamily: _family); // 关闭
  static const IconData diantaiguanli = IconData(0xe61d, fontFamily: _family); // 菜单-电台管理
  static const IconData wenjian = IconData(0xe61e, fontFamily: _family); // 文件
  static const IconData wenjianjia = IconData(0xe61f, fontFamily: _family); // 文件夹
  static const IconData shanchu = IconData(0xe620, fontFamily: _family); // 删除
  static const IconData che = IconData(0xe621, fontFamily: _family); // 车
  static const IconData xiala = IconData(0xe622, fontFamily: _family); // 下拉
  static const IconData canshujiazhu = IconData(0xe623, fontFamily: _family); // 菜单-参数加注
  static const IconData ren = IconData(0xe624, fontFamily: _family); // 人
  static const IconData zhihuisuo = IconData(0xe625, fontFamily: _family); // 指挥所
  static const IconData zhuyueqiangguanli = IconData(0xe626, fontFamily: _family); // 菜单-注钥枪管理
}

class _PreviewIcon {
  const _PreviewIcon(this.icon, this.name, this.propName);

  final IconData icon;
  final String name;
  final String propName;
}

class HyIconsPreview extends StatelessWidget {
  const HyIconsPreview({Key? key}) : super(key: key);

  static const iconList = <_PreviewIcon>[
    _PreviewIcon(HyIcons.gengduocaozuo, "gengduocaozuo", "更多操作"),
    _PreviewIcon(HyIcons.jiantou, "jiantou", "箭头"),
    _PreviewIcon(HyIcons.bianji, "bianji", "编辑"),
    _PreviewIcon(HyIcons.guanbi, "guanbi", "关闭"),
    _PreviewIcon(HyIcons.diantaiguanli, "diantaiguanli", "菜单-电台管理"),
    _PreviewIcon(HyIcons.wenjian, "wenjian", "文件"),
    _PreviewIcon(HyIcons.wenjianjia, "wenjianjia", "文件夹"),
    _PreviewIcon(HyIcons.shanchu, "shanchu", "删除"),
    _PreviewIcon(HyIcons.che, "che", "车"),
    _PreviewIcon(HyIcons.xiala, "xiala", "下拉"),
    _PreviewIcon(HyIcons.canshujiazhu, "canshujiazhu", "菜单-参数加注"),
    _PreviewIcon(HyIcons.ren, "ren", "人"),
    _PreviewIcon(HyIcons.zhihuisuo, "zhihuisuo", "指挥所"),
    _PreviewIcon(HyIcons.zhuyueqiangguanli, "zhuyueqiangguanli", "菜单-注钥枪管理"),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('HyIcons'),
      ),
      body: GridView.count(
        shrinkWrap: true,
        crossAxisCount: 4,
        children: iconList.map((e) {
          return InkWell(
            onTap: () {
              //
            },
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(
                  margin: const EdgeInsets.only(bottom: 8),
                  child: Icon(e.icon),
                ),
                Text(e.name, style: const TextStyle(fontSize: 12), overflow: TextOverflow.ellipsis, maxLines: 1),
                Text(e.propName, style: const TextStyle(fontSize: 12), overflow: TextOverflow.ellipsis, maxLines: 1),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }
}
