// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/entities/book/bookEntity.dart';
import 'core/entities/keyLoaderDetails/keyLoaderDetailsEntity.dart';
import 'core/entities/keyLoaders/keyLoadersEntity.dart';
import 'core/entities/radios/radiosEntity.dart';
import 'core/entities/user/userEntity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4228326011651379410),
    name: 'BookEntity',
    lastPropertyId: const obx_int.IdUid(4, 3302835863899312507),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8166113969912134000),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3554625101348728654),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4346021289038658759),
        name: 'authorId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 7435491961108656421),
        relationField: 'author',
        relationTarget: 'UserEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3302835863899312507),
        name: 'authorTargetId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8006931716750502718),
    name: 'UserEntity',
    lastPropertyId: const obx_int.IdUid(5, 6472168895729739469),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5794072510174123825),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8136205732470114287),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4857777868047644034),
        name: 'age',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1236374995590843085),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6472168895729739469),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'books',
        srcEntity: 'BookEntity',
        srcField: 'author',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 3041742923072573707),
    name: 'RadiosEntity',
    lastPropertyId: const obx_int.IdUid(7, 1938772858763471383),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8212549522126293471),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4353079850130922898),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3971463092837512991),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 720313766199209011),
        name: 'consumer',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3031192070671928960),
        name: 'location',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3312982194520429936),
        name: 'sn',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1938772858763471383),
        name: 'alias',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 3582610162093702077),
    name: 'KeyLoadersEntity',
    lastPropertyId: const obx_int.IdUid(8, 1971884064875378411),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4300435149840873),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 759719742253764922),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7851453332233287696),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5368222792800701576),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 1813780709103220274),
    name: 'KeyLoaderDetailsEntity',
    lastPropertyId: const obx_int.IdUid(13, 7777777777777777777),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3947670863590069697),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3710909501779793844),
        name: 'netNodePackageName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4846126622957901691),
        name: 'dcPackageName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3874646593090869108),
        name: 'keyLoaderId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8115624923809510147),
        name: 'radioId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7237388031547419600),
        name: 'consumer',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8445630818835119620),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4719075845335563294),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7584349726139528281),
        name: 'location',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1568432106393426332),
        name: 'SN',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7777777777777777777),
        name: 'parentIdPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(7, 1813780709103220274),
    lastIndexId: const obx_int.IdUid(2, 7248603694203076703),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [2827524875656266667, 6271279407079570812],
    retiredIndexUids: const [7248603694203076703],
    retiredPropertyUids: const [
      812668694605346950,
      7877995074749865462,
      7919633563325803080,
      4008391957519251833,
      6049395943988811899,
      7763530486178484550,
      2065786153626554741,
      4137391018581619396,
      7643555413760363020,
      7386054865052925963,
      1851302253626920133,
      8095231258585915719,
      8528062035017541503,
      1971884064875378411,
      5319821483848505265,
      7814641166435052936,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    BookEntity: obx_int.EntityDefinition<BookEntity>(
      model: _entities[0],
      toOneRelations: (BookEntity object) => [object.author],
      toManyRelations: (BookEntity object) => {},
      getId: (BookEntity object) => object.id,
      setId: (BookEntity object, int id) {
        object.id = id;
      },
      objectToFB: (BookEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addInt64(2, object.author.targetId);
        fbb.addInt64(3, object.authorTargetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = BookEntity(id: idParam, title: titleParam)
          ..authorTargetId = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            10,
          );
        object.author.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.author.attach(store);
        return object;
      },
    ),
    UserEntity: obx_int.EntityDefinition<UserEntity>(
      model: _entities[1],
      toOneRelations: (UserEntity object) => [],
      toManyRelations: (UserEntity object) => {
        obx_int.RelInfo<BookEntity>.toOneBacklink(
          3,
          object.id,
          (BookEntity srcObject) => srcObject.author,
        ): object.books,
      },
      getId: (UserEntity object) => object.id,
      setId: (UserEntity object, int id) {
        object.id = id;
      },
      objectToFB: (UserEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.age);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final ageParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = UserEntity(
          id: idParam,
          name: nameParam,
          age: ageParam,
          updatedAt: updatedAtParam,
          createdAt: createdAtParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<UserEntity>(
          object.books,
          store,
          obx_int.RelInfo<BookEntity>.toOneBacklink(
            3,
            object.id,
            (BookEntity srcObject) => srcObject.author,
          ),
        );
        return object;
      },
    ),
    RadiosEntity: obx_int.EntityDefinition<RadiosEntity>(
      model: _entities[2],
      toOneRelations: (RadiosEntity object) => [],
      toManyRelations: (RadiosEntity object) => {},
      getId: (RadiosEntity object) => object.id,
      setId: (RadiosEntity object, int id) {
        object.id = id;
      },
      objectToFB: (RadiosEntity object, fb.Builder fbb) {
        final consumerOffset = fbb.writeString(object.consumer);
        final locationOffset = fbb.writeString(object.location);
        final snOffset = fbb.writeString(object.sn);
        final aliasOffset = fbb.writeString(object.alias);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(2, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(3, consumerOffset);
        fbb.addOffset(4, locationOffset);
        fbb.addOffset(5, snOffset);
        fbb.addOffset(6, aliasOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final consumerParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final locationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final snParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final aliasParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object = RadiosEntity(
          id: idParam,
          consumer: consumerParam,
          location: locationParam,
          sn: snParam,
          alias: aliasParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    KeyLoadersEntity: obx_int.EntityDefinition<KeyLoadersEntity>(
      model: _entities[3],
      toOneRelations: (KeyLoadersEntity object) => [],
      toManyRelations: (KeyLoadersEntity object) => {},
      getId: (KeyLoadersEntity object) => object.id,
      setId: (KeyLoadersEntity object, int id) {
        object.id = id;
      },
      objectToFB: (KeyLoadersEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = KeyLoadersEntity(
          id: idParam,
          name: nameParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    KeyLoaderDetailsEntity: obx_int.EntityDefinition<KeyLoaderDetailsEntity>(
      model: _entities[4],
      toOneRelations: (KeyLoaderDetailsEntity object) => [],
      toManyRelations: (KeyLoaderDetailsEntity object) => {},
      getId: (KeyLoaderDetailsEntity object) => object.id,
      setId: (KeyLoaderDetailsEntity object, int id) {
        object.id = id;
      },
      objectToFB: (KeyLoaderDetailsEntity object, fb.Builder fbb) {
        final netNodePackageNameOffset = fbb.writeString(
          object.netNodePackageName,
        );
        final dcPackageNameOffset = fbb.writeString(object.dcPackageName);
        final consumerOffset = object.consumer == null
            ? null
            : fbb.writeString(object.consumer!);
        final locationOffset = object.location == null
            ? null
            : fbb.writeString(object.location!);
        final SNOffset = object.SN == null ? null : fbb.writeString(object.SN!);
        final parentIdPathOffset = fbb.writeString(object.parentIdPath);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, netNodePackageNameOffset);
        fbb.addOffset(2, dcPackageNameOffset);
        fbb.addInt64(3, object.keyLoaderId);
        fbb.addInt64(5, object.radioId);
        fbb.addOffset(6, consumerOffset);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(10, locationOffset);
        fbb.addOffset(11, SNOffset);
        fbb.addOffset(12, parentIdPathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final netNodePackageNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final dcPackageNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final keyLoaderIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final radioIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final consumerParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final locationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final SNParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final parentIdPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final object = KeyLoaderDetailsEntity(
          id: idParam,
          netNodePackageName: netNodePackageNameParam,
          dcPackageName: dcPackageNameParam,
          keyLoaderId: keyLoaderIdParam,
          radioId: radioIdParam,
          consumer: consumerParam,
          location: locationParam,
          SN: SNParam,
          parentIdPath: parentIdPathParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [BookEntity] entity fields to define ObjectBox queries.
class BookEntity_ {
  /// See [BookEntity.id].
  static final id = obx.QueryIntegerProperty<BookEntity>(
    _entities[0].properties[0],
  );

  /// See [BookEntity.title].
  static final title = obx.QueryStringProperty<BookEntity>(
    _entities[0].properties[1],
  );

  /// See [BookEntity.author].
  static final author = obx.QueryRelationToOne<BookEntity, UserEntity>(
    _entities[0].properties[2],
  );

  /// See [BookEntity.authorTargetId].
  static final authorTargetId = obx.QueryIntegerProperty<BookEntity>(
    _entities[0].properties[3],
  );
}

/// [UserEntity] entity fields to define ObjectBox queries.
class UserEntity_ {
  /// See [UserEntity.id].
  static final id = obx.QueryIntegerProperty<UserEntity>(
    _entities[1].properties[0],
  );

  /// See [UserEntity.name].
  static final name = obx.QueryStringProperty<UserEntity>(
    _entities[1].properties[1],
  );

  /// See [UserEntity.age].
  static final age = obx.QueryIntegerProperty<UserEntity>(
    _entities[1].properties[2],
  );

  /// See [UserEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<UserEntity>(
    _entities[1].properties[3],
  );

  /// See [UserEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<UserEntity>(
    _entities[1].properties[4],
  );

  /// see [UserEntity.books]
  static final books = obx.QueryBacklinkToMany<BookEntity, UserEntity>(
    BookEntity_.author,
  );
}

/// [RadiosEntity] entity fields to define ObjectBox queries.
class RadiosEntity_ {
  /// See [RadiosEntity.id].
  static final id = obx.QueryIntegerProperty<RadiosEntity>(
    _entities[2].properties[0],
  );

  /// See [RadiosEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<RadiosEntity>(
    _entities[2].properties[1],
  );

  /// See [RadiosEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<RadiosEntity>(
    _entities[2].properties[2],
  );

  /// See [RadiosEntity.consumer].
  static final consumer = obx.QueryStringProperty<RadiosEntity>(
    _entities[2].properties[3],
  );

  /// See [RadiosEntity.location].
  static final location = obx.QueryStringProperty<RadiosEntity>(
    _entities[2].properties[4],
  );

  /// See [RadiosEntity.sn].
  static final sn = obx.QueryStringProperty<RadiosEntity>(
    _entities[2].properties[5],
  );

  /// See [RadiosEntity.alias].
  static final alias = obx.QueryStringProperty<RadiosEntity>(
    _entities[2].properties[6],
  );
}

/// [KeyLoadersEntity] entity fields to define ObjectBox queries.
class KeyLoadersEntity_ {
  /// See [KeyLoadersEntity.id].
  static final id = obx.QueryIntegerProperty<KeyLoadersEntity>(
    _entities[3].properties[0],
  );

  /// See [KeyLoadersEntity.name].
  static final name = obx.QueryStringProperty<KeyLoadersEntity>(
    _entities[3].properties[1],
  );

  /// See [KeyLoadersEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<KeyLoadersEntity>(
    _entities[3].properties[2],
  );

  /// See [KeyLoadersEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<KeyLoadersEntity>(
    _entities[3].properties[3],
  );
}

/// [KeyLoaderDetailsEntity] entity fields to define ObjectBox queries.
class KeyLoaderDetailsEntity_ {
  /// See [KeyLoaderDetailsEntity.id].
  static final id = obx.QueryIntegerProperty<KeyLoaderDetailsEntity>(
    _entities[4].properties[0],
  );

  /// See [KeyLoaderDetailsEntity.netNodePackageName].
  static final netNodePackageName =
      obx.QueryStringProperty<KeyLoaderDetailsEntity>(
        _entities[4].properties[1],
      );

  /// See [KeyLoaderDetailsEntity.dcPackageName].
  static final dcPackageName = obx.QueryStringProperty<KeyLoaderDetailsEntity>(
    _entities[4].properties[2],
  );

  /// See [KeyLoaderDetailsEntity.keyLoaderId].
  static final keyLoaderId = obx.QueryIntegerProperty<KeyLoaderDetailsEntity>(
    _entities[4].properties[3],
  );

  /// See [KeyLoaderDetailsEntity.radioId].
  static final radioId = obx.QueryIntegerProperty<KeyLoaderDetailsEntity>(
    _entities[4].properties[4],
  );

  /// See [KeyLoaderDetailsEntity.consumer].
  static final consumer = obx.QueryStringProperty<KeyLoaderDetailsEntity>(
    _entities[4].properties[5],
  );

  /// See [KeyLoaderDetailsEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<KeyLoaderDetailsEntity>(
    _entities[4].properties[6],
  );

  /// See [KeyLoaderDetailsEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<KeyLoaderDetailsEntity>(
    _entities[4].properties[7],
  );

  /// See [KeyLoaderDetailsEntity.location].
  static final location = obx.QueryStringProperty<KeyLoaderDetailsEntity>(
    _entities[4].properties[8],
  );

  /// See [KeyLoaderDetailsEntity.SN].
  static final SN = obx.QueryStringProperty<KeyLoaderDetailsEntity>(
    _entities[4].properties[9],
  );

  /// See [KeyLoaderDetailsEntity.parentIdPath].
  static final parentIdPath = obx.QueryStringProperty<KeyLoaderDetailsEntity>(
    _entities[4].properties[10],
  );
}
